---
- name: update App.js file
  hosts: webapp

  tasks:
    - name: Update web page
      ansible.builtin.lineinfile:
        path: /hello-world/src/App.js
        regexp: '^Hello World!'
        line: 'Hello Devops!'