name: mywf

on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
    myfirstjob:
              name: My first job
              runs-on: ubuntu-latest
              steps:
              - name: Step one
                uses: actions/checkout@v3
              - name: Step two
                run: |
                  touch newfile.yaml
                  echo "this is my first action" >> newfile.yaml
                  cat newfile.yaml
                  pwd
    mysecondjob:
               needs: [myfirstjob]
               name: My second job
               runs-on: macos-latest
               steps:
               - name: Step one
                 run: date
    mythirdjob:
              name: My third job
              runs-on: windows-latest
              steps:
              - name: Step one
                run: date
