name: Test and Build

on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
    test:
        name: Test react
        runs-on: ubuntu-latest
        steps:
        - name: Step one
          uses: actions/checkout@v3
        - name: Set Node.js
          uses: actions/setup-node@v3
          with:
              node-version-file: './capstone_project/hello-world/.nvmrc'
        - run: cd ./capstone_project/hello-world && npm install
        - run: cd ./capstone_project/hello-world && npm test
    build:
          needs: [test]
          name: build docker image
          runs-on: ubuntu-latest
          steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: build image
            run: |
                docker build -f ./capstone_project/hello-world/Dockerfile -t devops-helloworld:v.1.0 ./capstone_project/hello-world

